### ISSUE TITLE
TypeError: routes.initialize is not a function

### ISSUE THREAD

**Issue by Mazuco** [PacktPublishing/Web-Development-with-MongoDB-and-Node-Third-Edition#3]
I'm tring in "Testing the application" > "Testing the routes" in Chapter09 and it result in this error:

root@mongo1:~/imgPloadr# npm test

> imgploadr@1.0.0 test /root/imgPloadr
> mocha -r tests/testhelper.js -R spec tests/**/*.test.js

  Routes
    GETs
      1) "before each" hook for "should handle /"

  0 passing (4ms)
  1 failing

  1) Routes
       "before each" hook for "should handle /":
     TypeError: routes.initialize is not a function
      at Context.<anonymous> (tests/server/routes.test.js:14:16)
      at processImmediate (internal/timers.js:439:21)

npm ERR! Test failed.  See above for more details.

**Comment by bron10** [comment]
Have you exported a method `initialize` from server/routes.js ? it is expected by your routes.test.js in `beforeEach` function. Please refer link : https://github.com/PacktPublishing/Web-Development-with-MongoDB-and-Node-Third-Edition/blob/master/Chapter09/server/routes.js

Let us know for more issues
